### PR TITLE
sos: fix TLS certificate issue on Windows

### LINKED ISSUE #189: Certificat error with exocli on Windows
Hi,

I get this error when I try to list my buckets from exocli.exe on Windows server.
```
C:\Users\Administrator\Downloads\exocli>exo.exe sos list
error: Get https://sos-ch-dk-2.exo.io/: x509: certificate signed by unknown authority
```
Regards,
Martial

### PR DESCRIPTION
**Pull request by falzm**
This change introduces a workaround to a bug in the Microsoft Windows
support in Go (https://github.com/golang/go/issues/16736). Some
heavily-chained certificates such as Exoscale SOS API's one are not
recognized as being signed by a trusted Certificate Authority.

Until the bug is fixed upstream, Windows users are required to use the
`--certs-file` flag with a path to a local file containing Exoscale SOS
API's certificate chain to the `exo sos` commands.

Fixes #189.

### CODE REVIEW

File: cmd/sos.go [hunk 1]
```diff
@@ -1,40 +1,142 @@
...
+IMPORTANT: Due to a bug in the Microsoft Windows support in the Go
+programming language (https://github.com/golang/go/issues/16736), some
+security certificates such as Exoscale SOS API's one are not recognized as
+being signed by a trusted Certificate Authority. In order to work around this
+issue until the bug is fixed upstream, Windows users are required to use the
+"--certs-file" flag with a path to a local file containing Exoscale SOS API's
+certificate chain to the "exo sos" commands. This file can be downloaded from
+the following address:
+
+	https://www.exoscale.com/sos.crt
```
Comment (falzm) [inline cmd/sos.go]: The actual address is up for debate, could be a link to the Community documentation. cc @llambiel @brutasse

**Comment by falzm** [comment]
[ch6732]

File: cmd/sos_create.go [hunk 2]
```diff
@@ -5,30 +5,27 @@ import (
...
 	"github.com/exoscale/egoscale"
-	minio "github.com/minio/minio-go/v6"
 	"github.com/spf13/cobra"
 )
 
 // createCmd represents the create command
 var sosCreateCmd = &cobra.Command{
 	Use:     "create <name>",
-	Short:   "create bucket",
+	Short:   "Create a bucket",
```
Comment (pierre-emmanuelJ) [inline cmd/sos_create.go]: thx

**Comment by falzm** [comment]
> LGTM, have you tested all refactored commands?

Yes, but feel free to do so on your end too :)

File: cmd/sos.go (hunk 1 above)
Comment (exo-cedric) [reply cmd/sos.go]: At some point (not so long in the future), we'll need some PKI-specific folder or hostname to distribute all PKI-related material (be it external, like the case at hand, or internal, if we choose to keep following that way).
(PS: this PKI material may be provided via an http**s**://... URI as long as there is no chicken-'n-egg problem)

Comment (falzm) [reply cmd/sos.go]: IIRC the `exoscale.com` cert is universally trusted, only the `*.exo.io` causes issues.
